<?php
// DATA PENYAKIT (disimpan dalam array)
$penyakit = [
    ['id' => 1, 'nama' => 'Absans (Lena)'],
    ['id' => 2, 'nama' => 'Abses Gigi'],
    ['id' => 3, 'nama' => 'Abses Peritonsil'],
    ['id' => 4, 'nama' => 'Abses Telinga (Abses Bezold)'],
    ['id' => 5, 'nama' => 'Acne Vulgaris (Jerawat)'],
    ['id' => 6, 'nama' => 'Acquired Imunodefciency Syndrome (AIDS/HIV)'],
    ['id' => 7, 'nama' => 'Acute Coronary Syndrome (Sindrom Koroner Akut)'],
    ['id' => 8, 'nama' => 'Adenoidits (Radang Kelenjar Adenoid)'],
    ['id' => 9, 'nama' => 'Alergi'],
    ['id' => 10, 'nama' => 'Alzheimer disease (Penyakit Alzheimer)'],
    ['id' => 11, 'nama' => 'Amyloidosis (Amiloidosis)'],
    ['id' => 12, 'nama' => 'Anal Abscess (Abses Anal)'],
    ['id' => 13, 'nama' => 'Aneurisma Aorta (Pelebaran Abnormal Aorta)'],
    ['id' => 14, 'nama' => 'Angina Pectoris (Serangan Jantung)'],
    ['id' => 15, 'nama' => 'Angioedema (Bengkak Pembuluh Darah Bawah Kulit)'],
    ['id' => 16, 'nama' => 'Anoreksia Nervosa'],
    ['id' => 17, 'nama' => 'Aritmia (Gangguan Irama Jantung)'],
    ['id' => 18, 'nama' => 'Arthris Rheumatoid'],
    ['id' => 19, 'nama' => 'Asam Urat (Arthris Gout)'],
    ['id' => 20, 'nama' => 'Asma Bronkhiale'],
    ['id' => 21, 'nama' => 'Atresia Ani (Cacat Lubang Anus)'],
    ['id' => 22, 'nama' => 'Ausme (Ausm)'],
    ['id' => 23, 'nama' => 'Baby Blues (Postpartum Blues)'],
    ['id' => 24, 'nama' => 'Batu Empedu (Gallstone)'],
    ['id' => 25, 'nama' => 'Batu Ginjal (Kidney Stone)'],
    ['id' => 26, 'nama' => 'Batu Kandung Kemih (Vesikoliasis)'],
    ['id' => 27, 'nama' => 'Batu Saluran Kemih (Ureteroliasis)'],
    ['id' => 28, 'nama' => 'Batuk Rejan (Pertusis)'],
    ['id' => 29, 'nama' => 'Bayi kuning karena Menyusui (Breastmilk Jaundice)'],
    ['id' => 30, 'nama' => 'Bell\'s Palsy'],
    ['id' => 31, 'nama' => 'Bengkak di lipat paha/Bubo Inguinalis (LGV)'],
    ['id' => 32, 'nama' => 'Benjolan kelopak mata (Kalazion)'],
    ['id' => 33, 'nama' => 'Breasfeed Jaundice'],
    ['id' => 34, 'nama' => 'Bronkis'],
    ['id' => 35, 'nama' => 'Bubo Ingunalis'],
    ['id' => 36, 'nama' => 'Bulimia Nervosa'],
    ['id' => 37, 'nama' => 'Cacar Air (Varicella / Chickenpox)'],
    ['id' => 38, 'nama' => 'Cacar ular (Herpes zoster)'],
    ['id' => 39, 'nama' => 'Cairan Terakumulasi di Rongga Pleura (Eusi Pleura)'],
    ['id' => 40, 'nama' => 'Campak (morbili)'],
    ['id' => 41, 'nama' => 'Carpal Tunnel Syndrome'],
    ['id' => 42, 'nama' => 'Cedera Lutut'],
    ['id' => 43, 'nama' => 'Crohn Disease'],
    ['id' => 44, 'nama' => 'Cushing Syndrome'],
    ['id' => 45, 'nama' => 'Cutaneous Larva Migrans'],
    ['id' => 46, 'nama' => 'Dakrioadenis (Radang Kelenjar Air Mata)'],
    ['id' => 47, 'nama' => 'Dakriosis s (Radang Saluran Air Mata)'],
    ['id' => 48, 'nama' => 'Defsiensi Glukosa-6-Fosfat Dehidrogenase (G6PD Defciency)'],
    ['id' => 49, 'nama' => 'Defsiensi Vitamin B1 (Beri-beri)'],
    ['id' => 50, 'nama' => 'Dehidrasi/Kurang Cairan'],
    ['id' => 51, 'nama' => 'Demam Berdarah Dengue (DBD / DHF)'],
    ['id' => 52, 'nama' => 'Demam Kuning (Yellow Fever)'],
    ['id' => 53, 'nama' => 'Demam Reumak'],
    ['id' => 54, 'nama' => 'Demam Tioid (Typhoid Fever)'],
    ['id' => 55, 'nama' => 'Depresi (Depression)'],
    ['id' => 56, 'nama' => 'Dexamfetamine'],
    ['id' => 57, 'nama' => 'Dexbrompheniramine'],
    ['id' => 58, 'nama' => 'Dexefmide'],
    ['id' => 59, 'nama' => 'Dexibuprofen'],
    ['id' => 60, 'nama' => 'Dexlansoprazole'],
    ['id' => 61, 'nama' => 'Dexmedetomidine'],
    ['id' => 62, 'nama' => 'Dexpanthenol'],
    ['id' => 63, 'nama' => 'Dextran'],
    ['id' => 64, 'nama' => 'Dextropropoxyphene'],
    ['id' => 65, 'nama' => 'Diabetes Gestasional'],
    ['id' => 66, 'nama' => 'Diabetes Tipe I (DM pe 1)'],
    ['id' => 67, 'nama' => 'Diabetes pe II (DM Tipe 2)'],
    ['id' => 68, 'nama' => 'Diacerein'],
    ['id' => 69, 'nama' => 'Diare (mencret-mencret)'],
    ['id' => 70, 'nama' => 'Diaxozide'],
    ['id' => 71, 'nama' => 'Dibekacin'],
    ['id' => 72, 'nama' => 'Dibenzepin'],
    ['id' => 73, 'nama' => 'Dicycloverine'],
    ['id' => 74, 'nama' => 'Didanosine'],
    ['id' => 75, 'nama' => 'Dienestrol'],
    ['id' => 76, 'nama' => 'Dienogest'],
    ['id' => 77, 'nama' => 'Diethylamine Salicylate'],
    ['id' => 78, 'nama' => 'Diethylslbestrol'],
    ['id' => 79, 'nama' => 'Difemerine'],
    ['id' => 80, 'nama' => 'Diferi'],
    ['id' => 81, 'nama' => 'Disentri amuba'],
    ['id' => 82, 'nama' => 'Disfungsi Ereksi (Erecle Dysfuncon)'],
    ['id' => 83, 'nama' => 'Eksem (Eczema)'],
    ['id' => 84, 'nama' => 'Elephanasis (Penyakit Kaki Gajah)'],
    ['id' => 85, 'nama' => 'Encok (Low Back Pain)'],
    ['id' => 86, 'nama' => 'Entomophobia (Takut Serangga)'],
    ['id' => 87, 'nama' => 'Epilepsy (Epilepsi)'],
    ['id' => 88, 'nama' => 'Fibrilasi Ventrikel'],
    ['id' => 89, 'nama' => 'Fibroadenoma Mammae (Tumor Jinak Payudara)'],
    ['id' => 90, 'nama' => 'Filariasis (Kaki Gajah)'],
    ['id' => 91, 'nama' => 'Fistula Ani'],
    ['id' => 92, 'nama' => 'Fistula Pre-aurikular (Penyakit Bawaan pada Telinga)'],
    ['id' => 93, 'nama' => 'Flu Burung (Avian Inuenza / H5N1)'],
    ['id' => 94, 'nama' => 'Flu singapura (Hand, Foot, and Mouth Disease)'],
    ['id' => 95, 'nama' => 'Fraktur Basis Kranii (Patah tulang dasar tengkorak)'],
    ['id' => 96, 'nama' => 'Fraktur Cervical (Patah tulang leher)'],
    ['id' => 97, 'nama' => 'Fraktur Humerus (Patah tulang lengan atas)'],
    ['id' => 98, 'nama' => 'Fraktur Penis'],
    ['id' => 99, 'nama' => 'Gagal Ginjal Akut (Acute Renal Failure / GGA)'],
    ['id' => 100, 'nama' => 'Gagal Ginjal Kronik (Chronic Renal Failure / CKD)'],
    ['id' => 101, 'nama' => 'Gagal Jantung'],
    ['id' => 102, 'nama' => 'Gangguan aliran darah Vena (Insufsiensi vena kronik)'],
    ['id' => 103, 'nama' => 'Gangguan Dismorfk Tubuh'],
    ['id' => 104, 'nama' => 'Gangguan Hormon Tiroid (Hipoiroid)'],
    ['id' => 105, 'nama' => 'Gangguan Kecemasan (Anxietas)'],
    ['id' => 106, 'nama' => 'Gangguan Menstruasi (Menorrhagia)'],
    ['id' => 107, 'nama' => 'Gangguan pergerakan lambung (Gastroparesis)'],
    ['id' => 108, 'nama' => 'Gangguan Saraf Perier Kaki atau Tangan (Peripheral Neuropathy/Neuropa perier)'],
    ['id' => 109, 'nama' => 'Gangguan sirkulasi darah anggota gerak bawah (Crcal limb ischemia/CLI)'],
    ['id' => 110, 'nama' => 'Gangguan usus besar kronis (Irritable Bowel Syndrome/IBS)'],
    ['id' => 111, 'nama' => 'Gangren Pedis'],
    ['id' => 112, 'nama' => 'Gizi Buruk Tipe Marasmus'],
    ['id' => 113, 'nama' => 'Gondongan (MUMPS)'],
    ['id' => 114, 'nama' => 'Hemangioma (Tumor pembuluh darah)'],
    ['id' => 115, 'nama' => 'Hepa s A'],
    ['id' => 116, 'nama' => 'Hernia'],
    ['id' => 117, 'nama' => 'Hernia Lateralis'],
    ['id' => 118, 'nama' => 'Hernia Skrotalis'],
    ['id' => 119, 'nama' => 'Hernia Umbilikalis'],
    ['id' => 120, 'nama' => 'Herpes kelamin / genital (Herpes Simpleks)'],
    ['id' => 121, 'nama' => 'Herpes Mulut (Herpes Oral)'],
    ['id' => 122, 'nama' => 'Herpes Zoster pada Telinga (Sindrom Ramsay Hunt)'],
    ['id' => 123, 'nama' => 'Hidronefrosis atau Pembengkakan pada Ginjal'],
    ['id' => 124, 'nama' => 'Hidrosefalus (Hydrocephalus)'],
    ['id' => 125, 'nama' => 'Hipertensi (Darah Tinggi)'],
    ['id' => 126, 'nama' => 'Hipertensi Urgensi'],
    ['id' => 127, 'nama' => 'Hiperroid'],
    ['id' => 128, 'nama' => 'Hipokondriasis (Merasa Memiliki Sakit Berat)'],
    ['id' => 129, 'nama' => 'Hordeolum'],
    ['id' => 130, 'nama' => 'Ileus'],
    ['id' => 131, 'nama' => 'Imun Trombositopenia Purpura (ITP)'],
    ['id' => 132, 'nama' => 'Infeksi Alat Kelamin (Chancroid atau Ulkus Mole)'],
    ['id' => 133, 'nama' => 'Infeksi Cacing (Askariasis)'],
    ['id' => 134, 'nama' => 'Infeksi Cacing Kremi (Enterobiasis)'],
    ['id' => 135, 'nama' => 'Infeksi Cacing Tambang / Ancylostomiasis'],
    ['id' => 136, 'nama' => 'Infeksi Cytomegalovirus'],
    ['id' => 137, 'nama' => 'Infeksi Epstein-Barr virus (Mononukleosis / Kissing disease)'],
    ['id' => 138, 'nama' => 'Infeksi karena kuman Leptospira / Leptospirosis'],
    ['id' => 139, 'nama' => 'Infeksi Kulit (Impego)'],
    ['id' => 140, 'nama' => 'Infeksi parasit Giardia di usus (Giardiasis)'],
    ['id' => 141, 'nama' => 'Infeksi Saluran Kemih (Urinary Tract Infec on)'],
    ['id' => 142, 'nama' => 'Infeksi saluran nafas atas bayi (Croup/Laringotrakeobronkis)'],
    ['id' => 143, 'nama' => 'Infeksi Tali Pusat (Omfalis)'],
    ['id' => 144, 'nama' => 'Infeksi telinga'],
    ['id' => 145, 'nama' => 'Infeksi Telinga Bagian Tengah (Os Media Eusi)'],
    ['id' => 146, 'nama' => 'Infeksi Uretra/saluran kencing (Uretris)'],
    ['id' => 147, 'nama' => 'Infer litas'],
    ['id' => 148, 'nama' => 'Inamasi jaringan otak (Ensefalis)'],
    ['id' => 149, 'nama' => 'Inkonnensia Usus (Bowel Inconnence)'],
    ['id' => 150, 'nama' => 'Jamur kepala (Tinea kapis)'],
    ['id' => 151, 'nama' => 'Jamur kuku ( Nail fungus)'],
    ['id' => 152, 'nama' => 'Jamur lipat paha (Tinea Cruris)'],
    ['id' => 153, 'nama' => 'Juvenile Arthris (Radang Sendi Usia Muda)'],
    ['id' => 154, 'nama' => 'Kandidiasis Mulut (Oral Thrush)'],
    ['id' => 155, 'nama' => 'Kanker Darah (Leukemia)'],
    ['id' => 156, 'nama' => 'Kanker Ha (Carsinoma Hepar)'],
    ['id' => 157, 'nama' => 'Kanker Nasofaring'],
    ['id' => 158, 'nama' => 'Kanker Ovarium (Ovarian Cancer)'],
    ['id' => 159, 'nama' => 'Kanker Paru'],
    ['id' => 160, 'nama' => 'Kanker payudara (carsinoma mammae)'],
    ['id' => 161, 'nama' => 'Kanker prostat (Prostat Cancer)'],
    ['id' => 162, 'nama' => 'Kanker Serviks (Cervical Cancer)'],
    ['id' => 163, 'nama' => 'Kanker usus besar dan rektum / Kolorektal'],
    ['id' => 164, 'nama' => 'Karsinoma Tiroid (Kanker roid)'],
    ['id' => 165, 'nama' => 'Katarak'],
    ['id' => 166, 'nama' => 'Kegagalan Kontrol Buang Air Kecil / Inkonnensia Urine'],
    ['id' => 167, 'nama' => 'Keguguran (Abortus)'],
    ['id' => 168, 'nama' => 'Keguguran Berulang (Abortus Habitualis)'],
    ['id' => 169, 'nama' => 'Kehamilan Ektopik (Hamil di Luar Rahim)'],
    ['id' => 170, 'nama' => 'Kejang Demam'],
    ['id' => 171, 'nama' => 'Kejang Demam Kompleks'],
    ['id' => 172, 'nama' => 'Kejang Demam Sederhana'],
    ['id' => 173, 'nama' => 'Kelainan anatomi usus (Invaginasi usus)'],
    ['id' => 174, 'nama' => 'Kelainan Bawaan Lubang Uretra (Epispadia)'],
    ['id' => 175, 'nama' => 'Kelainan bawaan pada otak anak (Cerebral Palsy atau CP)'],
    ['id' => 176, 'nama' => 'Kelainan Bawaan pada Usus Besar (Hirschsprung Disease)'],
    ['id' => 177, 'nama' => 'Kelainan Genek pada Darah (Hemoflia)'],
    ['id' => 178, 'nama' => 'Kelainan Katup Jantung (Atresia Trikuspid)'],
    ['id' => 179, 'nama' => 'Kelainan letak saluran kemih (Epispadia)'],
    ['id' => 180, 'nama' => 'Kelainan letak saluran kemih (Hipospadia)'],
    ['id' => 181, 'nama' => 'Kelainan lokasi tumbuh jaringan rahim (Endometriosis)'],
    ['id' => 182, 'nama' => 'Kelopak mata terlipat ke dalam (Entropion)'],
    ['id' => 183, 'nama' => 'Kelopak Mata Terlipat Keluar (Ektropion)'],
    ['id' => 184, 'nama' => 'Kenali Gejala dan Pengobatan Radang Hidung Karena Obat (Rhins Medikamentosa)'],
    ['id' => 185, 'nama' => 'Kencing Nanah / Gonorrhoea'],
    ['id' => 186, 'nama' => 'Kepribadian Cemas Menghindar (Avoidant Personality Disorder)'],
    ['id' => 187, 'nama' => 'Kepuhan / Kandidiasis Vagina'],
    ['id' => 188, 'nama' => 'Keras'],
    ['id' => 189, 'nama' => 'Kerion (Peradangan Kepala Berat)'],
    ['id' => 190, 'nama' => 'Kerontokan abnormal rambut kepala (Alopecia Areata)'],
    ['id' => 191, 'nama' => 'Kerusakan autoimun sel saraf (Guillain Barre Syndrome)'],
    ['id' => 192, 'nama' => 'Kista Bartolini (Kista Dinding Vagina)'],
    ['id' => 193, 'nama' => 'Klaustrophobia (Phobia Ruang Sempit)'],
    ['id' => 194, 'nama' => 'Koledokoliasis (Batu Saluran Empedu)'],
    ['id' => 195, 'nama' => 'Kolera (Cholera)'],
    ['id' => 196, 'nama' => 'Kolesiss (Radang Saluran Empedu)'],
    ['id' => 197, 'nama' => 'Konjungvis'],
    ['id' => 198, 'nama' => 'Kudis (Scabies)'],
    ['id' => 199, 'nama' => 'Kul kelamin (Genital Warts)'],
    ['id' => 200, 'nama' => 'Kutu rambut / Pedikulosis kapis'],
    ['id' => 201, 'nama' => 'Labirinis (Infeksi Telinga Dalam)'],
    ['id' => 202, 'nama' => 'Lactose Intolerance (Intoleransi Laktosa)'],
    ['id' => 203, 'nama' => 'Laringis'],
    ['id' => 204, 'nama' => 'Lecet pada Pung Payudara (Cracked Nipple)'],
    ['id' => 205, 'nama' => 'Lepas / Ablasio rena'],
    ['id' => 206, 'nama' => 'Leprae (Morbus hansen)'],
    ['id' => 207, 'nama' => 'Limfoma (Limfocarcinoma)'],
    ['id' => 208, 'nama' => 'Lipoma (Tumor Kelenjar Lemak)'],
    ['id' => 209, 'nama' => 'Luka / Ulkus kornea'],
    ['id' => 210, 'nama' => 'Lupus Eritematosus Sistemik'],
    ['id' => 211, 'nama' => 'Malaria'],
    ['id' => 212, 'nama' => 'Mallory Weiss Syndrome (Perdarahan Saluran Cerna Atas)'],
    ['id' => 213, 'nama' => 'Masokisme (Kesenangan Seksual dengan Rasa Sakit)'],
    ['id' => 214, 'nama' => 'Mass (Radang jaringan payudara)'],
    ['id' => 215, 'nama' => 'Metroragia'],
    ['id' => 216, 'nama' => 'Miastenia Gravis'],
    ['id' => 217, 'nama' => 'Migrain'],
    ['id' => 218, 'nama' => 'Miringis Bulosa (Radang Gendang Telinga)'],
    ['id' => 219, 'nama' => 'Mola Hidadosa (Hamil Anggur)'],
    ['id' => 220, 'nama' => 'Morning Sickness'],
    ['id' => 221, 'nama' => 'Muntah berlebihan pada kehamilan (Hiperemesis gravidarum)'],
    ['id' => 222, 'nama' => 'Neuralgia post herpek'],
    ['id' => 223, 'nama' => 'Neuralgia Trigeminalis'],
    ['id' => 224, 'nama' => 'Neuroma Akusk / Acousc Neuroma (Vesbular Schwannoma)'],
    ['id' => 225, 'nama' => 'Nodul Tiroid'],
    ['id' => 226, 'nama' => 'Nyeri Kepala Kluster'],
    ['id' => 227, 'nama' => 'Nyeri Kepala Tipe Cluster (Cluster Headache)'],
    ['id' => 228, 'nama' => 'Nyeri Panggul Kronis (Chronic Pelvic Pain)'],
    ['id' => 229, 'nama' => 'Nyeri tulang dan otot (Fibromyalgia)'],
    ['id' => 230, 'nama' => 'Obstrucve Sleep Apnea'],
    ['id' => 231, 'nama' => 'Oklusi arteri perier extremitas inerior'],
    ['id' => 232, 'nama' => 'Oligomenorrhea (Gangguan Siklus Haid)'],
    ['id' => 233, 'nama' => 'Osteoarthris'],
    ['id' => 234, 'nama' => 'Os Externa (Radang Telinga)'],
    ['id' => 235, 'nama' => 'Os Externa Sirkumskripta'],
    ['id' => 236, 'nama' => 'Otosklerosis (Pertumbuhan Tulang Telinga Tengah Abnormal)'],
    ['id' => 237, 'nama' => 'Pankreas'],
    ['id' => 238, 'nama' => 'Panu (Tinea vesikolor)'],
    ['id' => 239, 'nama' => 'Patah lengan bawah / Fraktur Antebrachii'],
    ['id' => 240, 'nama' => 'Patah Tulang Paha / Fraktur Femur'],
    ['id' => 241, 'nama' => 'Patah Tungkai Bawah / Fraktur Kruris'],
    ['id' => 242, 'nama' => 'Pelebaran pembuluh darah vena (Varises)'],
    ['id' => 243, 'nama' => 'Pembengkakan skrotum (Hidrokel Tess)'],
    ['id' => 244, 'nama' => 'Pembesaran prostat / Benign Prosta c Hyperplasia (BPH)'],
    ['id' => 245, 'nama' => 'Penyakit asam lambung naik / reuks (GERD)'],
    ['id' => 246, 'nama' => 'Penyakit Autoimun pada Selubung Saraf (Mulple Sclerosis)'],
    ['id' => 247, 'nama' => 'Penyakit Gangguan Metabolik'],
    ['id' => 248, 'nama' => 'Penyakit Jantung Bawaan (Tetralogy O Fallot)'],
    ['id' => 249, 'nama' => 'Penyakit kelenjar roid (Graves Disease)'],
    ['id' => 250, 'nama' => 'Penyakit kulit kronis (Neurodermas)'],
    ['id' => 251, 'nama' => 'Penyakit Membran Hialin'],
    ['id' => 252, 'nama' => 'Penyakit Parkinson (Parkinson\'s Disease)'],
    ['id' => 253, 'nama' => 'Penyakit Paru Obstruk f Kronis (PPOK / COPD)'],
    ['id' => 254, 'nama' => 'Penyakit pembuluh arteri dan vena (Buerger disease)'],
    ['id' => 255, 'nama' => 'Penyakit pembuluh darah kecil (Raynaud\'s disease)'],
    ['id' => 256, 'nama' => 'Penyakit tabung saraf / Tarsal Tunnel Syndrome'],
    ['id' => 257, 'nama' => 'Penyakit tekanan pada bola mata (Glaukoma) Akut'],
    ['id' => 258, 'nama' => 'Penyempitan Uretra (Striktur Uretra)'],
    ['id' => 259, 'nama' => 'Peradangan pada Ginjal (Pielonefris)'],
    ['id' => 260, 'nama' => 'Peradangan pada Tendon Achilles (Achilles Tendinis)'],
    ['id' => 261, 'nama' => 'Peradangan Pembuluh Darah Kecil (Henoch Schonlein Purpura)'],
    ['id' => 262, 'nama' => 'Perdarahan mata (Hifema)'],
    ['id' => 263, 'nama' => 'Perdarahan Subkonjungva'],
    ['id' => 264, 'nama' => 'Perimenopause'],
    ['id' => 265, 'nama' => 'Periperal Neuropathy (Penyakit Saraf Tepi)'],
    ['id' => 266, 'nama' => 'Phlebis (Peradangan Pembuluh Darah Vena)'],
    ['id' => 267, 'nama' => 'Pica'],
    ['id' => 268, 'nama' => 'Pikun (Demensia)'],
    ['id' => 269, 'nama' => 'Pilek (Common Cold)'],
    ['id' => 270, 'nama' => 'Pinguekula (Penyakit Selaput Mata)'],
    ['id' => 271, 'nama' => 'Plasenta Previa (Perdarahan pada Kehamilan Tua)'],
    ['id' => 272, 'nama' => 'Pleuris (Radang Selaput Paru)'],
    ['id' => 273, 'nama' => 'Pneumokoniosis (Penyakit Paru Akibat Debu Kerja)'],
    ['id' => 274, 'nama' => 'Pneumonia (Radang paru)'],
    ['id' => 275, 'nama' => 'Polimenorea (Gangguan Siklus Haid)'],
    ['id' => 276, 'nama' => 'Poliomielis (Penyakit Infeksi Sumsum Tulang)'],
    ['id' => 277, 'nama' => 'Polip Hidung'],
    ['id' => 278, 'nama' => 'Polycysc Ovary Syndrome (PCOS)'],
    ['id' => 279, 'nama' => 'Pre-Menstrual Syndrome (PMS)'],
    ['id' => 280, 'nama' => 'Presbiakusis (Gangguan Pendengaran Usia Lanjut)'],
    ['id' => 281, 'nama' => 'Presbiopia (Mata Tua)'],
    ['id' => 282, 'nama' => 'Proks (Radang pada Anus)'],
    ['id' => 283, 'nama' => 'Pterigium'],
    ['id' => 284, 'nama' => 'Pusing Tujuh Keliling (Vergo)'],
    ['id' => 285, 'nama' => 'Pung Terbenam (Inverted Nipple)'],
    ['id' => 286, 'nama' => 'Rabun Dekat (Hipermetropia)'],
    ['id' => 287, 'nama' => 'Rabun Jauh (Miopia)'],
    ['id' => 288, 'nama' => 'Radang folikel rambut (Folikulis)'],
    ['id' => 289, 'nama' => 'Radang gusi (Gingivis)'],
    ['id' => 290, 'nama' => 'Radang kantung sendi (Bursis)'],
    ['id' => 291, 'nama' => 'Radang kelenjar limfe / Limfadenis'],
    ['id' => 292, 'nama' => 'Radang lambung (Gastris)'],
    ['id' => 293, 'nama' => 'Radang prostat (Prostas)'],
    ['id' => 294, 'nama' => 'Radang saluran kelamin (Epididimis)'],
    ['id' => 295, 'nama' => 'Radang Saluran Paru Bronkiolus (Bronkiolis)'],
    ['id' => 296, 'nama' => 'Radang selaput otak (Viral Meningis)'],
    ['id' => 297, 'nama' => 'Radang tenggorokan (Faringis)'],
    ['id' => 298, 'nama' => 'Radang usus (Ulcera ve Colis)'],
    ['id' => 299, 'nama' => 'Reumatoid Artrs'],
    ['id' => 300, 'nama' => 'Rhins Non-Alergi (Non-Allergic Rhins)'],
    ['id' => 301, 'nama' => 'Robek jaringan ginjal (Ruptur ginjal)'],
    ['id' => 302, 'nama' => 'Ruam Popok ( Diaper Rash)'],
    ['id' => 303, 'nama' => 'Sadisme'],
    ['id' => 304, 'nama' => 'Sakit Kepala (Headache)'],
    ['id' => 305, 'nama' => 'Sakit Lambung (Dispepsia atau Maag)'],
    ['id' => 306, 'nama' => 'Saraf Terjepit / Herniasi Nukleus Pulposus (HNP)'],
    ['id' => 307, 'nama' => 'Sariawan (Stomas)'],
    ['id' => 308, 'nama' => 'Scalp Psoriasis'],
    ['id' => 309, 'nama' => 'Sembelit (Kons pasi)'],
    ['id' => 310, 'nama' => 'Sengatan panas (Heat Stroke)'],
    ['id' => 311, 'nama' => 'Serangan panik (Panick Aack)'],
    ['id' => 312, 'nama' => 'Siflis (Raja Singa)'],
    ['id' => 313, 'nama' => 'Siflis Sekunder'],
    ['id' => 314, 'nama' => 'Silindris (Asgmasme)'],
    ['id' => 315, 'nama' => 'Sindrom tulang servikal (Cervical syndrome)'],
    ['id' => 316, 'nama' => 'Sinusis wajah'],
    ['id' => 317, 'nama' => 'Sirosis Hepas'],
    ['id' => 318, 'nama' => 'Solusio Plasenta (Perdarahan pada Kehamilan)'],
    ['id' => 319, 'nama' => 'Somasasi'],
    ['id' => 320, 'nama' => 'Somnambulisme'],
    ['id' => 321, 'nama' => 'Spondilis TB (Infeksi Tulang Belakang)'],
    ['id' => 322, 'nama' => 'Status Epilepkus'],
    ['id' => 323, 'nama' => 'Stenosis Pylorus'],
    ['id' => 324, 'nama' => 'Stroke (Kelumpuhan pada tubuh)'],
    ['id' => 325, 'nama' => 'Subdural Hematom'],
    ['id' => 326, 'nama' => 'Tension Type Headache (Nyeri Kepala Tipe Tegang)'],
    ['id' => 327, 'nama' => 'Tess Terpunr atau Torsio Tess'],
    ['id' => 328, 'nama' => 'Tess Tidak Turun (Kriptorkidismus)'],
    ['id' => 329, 'nama' => 'Tidur berlebihan (Hipersomnia)'],
    ['id' => 330, 'nama' => 'Tonsilis Diferi (Radang Tonsil)'],
    ['id' => 331, 'nama' => 'Torsio Tess (Tess Terpunr)'],
    ['id' => 332, 'nama' => 'Torkolis (Kaku Otot Leher)'],
    ['id' => 333, 'nama' => 'Transient Ischemic Aack (TIA)'],
    ['id' => 334, 'nama' => 'Transient Takipneu o Newborn (TTN)'],
    ['id' => 335, 'nama' => 'Trikiasis (Bulu Mata Tumbuh ke Dalam)'],
    ['id' => 336, 'nama' => 'Trikolomania (Perilaku Mencabut Rambut Berlebihan)'],
    ['id' => 337, 'nama' => 'Tuberkulosis Paru (TBC)'],
    ['id' => 338, 'nama' => 'Tuli Konduk f '],
    ['id' => 339, 'nama' => 'Tuli Sensorineural'],
    ['id' => 340, 'nama' => 'Tumor (Benjolan)'],
    ['id' => 341, 'nama' => 'Tumor ginjal (Tumor Wilms)'],
    ['id' => 342, 'nama' => 'Tumor jinak pembuluh darah (Angiofbroma)'],
    ['id' => 343, 'nama' => 'Tumor Paros (Kelenjar Ludah Besar)'],
    ['id' => 344, 'nama' => 'Ulkus Duodenum'],
    ['id' => 345, 'nama' => 'Ulkus Pepkum'],
    ['id' => 346, 'nama' => 'Urin kemerahan (Hematuria)'],
    ['id' => 347, 'nama' => 'Urkaria (Biduran)'],
    ['id' => 348, 'nama' => 'Usus Buntu (Apendisis)'],
    ['id' => 349, 'nama' => 'Usus Terpunr (Volvulus)'],
    ['id' => 350, 'nama' => 'Vaginal discharge'],
    ['id' => 351, 'nama' => 'Vaginismus (Problem Seksual Wanita)'],
    ['id' => 352, 'nama' => 'Vaginis'],
    ['id' => 353, 'nama' => 'Vaginosis Bakteri (Infeksi Bakteri pada Vagina)'],
    ['id' => 354, 'nama' => 'Varikokel (Pelebaran Pembuluh Vena Tess)'],
    ['id' => 355, 'nama' => 'Voyeurisme (Problem Psikiatri)'],
    ['id' => 356, 'nama' => 'Wasir / ambeien (Haemorrhoid)'],
    ['id' => 357, 'nama' => 'Xanthelasma (Gumpalan Lemak Kelopak Mata)'],
];

// DATA OBAT (disimpan dalam array)
$obat = [
    ['id' => 1, 'nama' => 'Acarbose', 'abjad' => 'A'],
    ['id' => 2, 'nama' => 'Acetazolamide', 'abjad' => 'A'],
    ['id' => 3, 'nama' => 'Acetylcysteine', 'abjad' => 'A'],
    ['id' => 4, 'nama' => 'Acrivasne', 'abjad' => 'A'],
    ['id' => 5, 'nama' => 'Acyclover Topical', 'abjad' => 'A'],
    ['id' => 6, 'nama' => 'Acyclovir', 'abjad' => 'A'],
    ['id' => 7, 'nama' => 'Albendazole', 'abjad' => 'A'],
    ['id' => 8, 'nama' => 'Albumin', 'abjad' => 'A'],
    ['id' => 9, 'nama' => 'Alginic Acid', 'abjad' => 'A'],
    ['id' => 10, 'nama' => 'Allopurinol', 'abjad' => 'A'],
    ['id' => 11, 'nama' => 'Allylestrenol', 'abjad' => 'A'],
    ['id' => 12, 'nama' => 'Alpha-Lipoic Acid', 'abjad' => 'A'],
    ['id' => 13, 'nama' => 'Alprazolam', 'abjad' => 'A'],
    ['id' => 14, 'nama' => 'Aluminium Hidroksida', 'abjad' => 'A'],
    ['id' => 15, 'nama' => 'Ambroxol', 'abjad' => 'A'],
    ['id' => 16, 'nama' => 'Amikacin', 'abjad' => 'A'],
    ['id' => 17, 'nama' => 'Aminepne', 'abjad' => 'A'],
    ['id' => 18, 'nama' => 'Aminoflin', 'abjad' => 'A'],
    ['id' => 19, 'nama' => 'Amiodarone', 'abjad' => 'A'],
    ['id' => 20, 'nama' => 'Amitriptyline', 'abjad' => 'A'],
    ['id' => 21, 'nama' => 'Amlodipine', 'abjad' => 'A'],
    ['id' => 22, 'nama' => 'Amonium Klorida', 'abjad' => 'A'],
    ['id' => 23, 'nama' => 'Amoxapine', 'abjad' => 'A'],
    ['id' => 24, 'nama' => 'Amoxicillin', 'abjad' => 'A'],
    ['id' => 25, 'nama' => 'Amphotericin B', 'abjad' => 'A'],
    ['id' => 26, 'nama' => 'Ampicillin', 'abjad' => 'A'],
    ['id' => 27, 'nama' => 'Anidulafungin', 'abjad' => 'A'],
    ['id' => 28, 'nama' => 'Apixaban', 'abjad' => 'A'],
    ['id' => 29, 'nama' => 'Arginine', 'abjad' => 'A'],
    ['id' => 30, 'nama' => 'Aripiprazole', 'abjad' => 'A'],
    ['id' => 31, 'nama' => 'Asam Alginat', 'abjad' => 'A'],
    ['id' => 32, 'nama' => 'Asam Amino', 'abjad' => 'A'],
    ['id' => 33, 'nama' => 'Asam Borat', 'abjad' => 'A'],
    ['id' => 34, 'nama' => 'Asam Glikolat', 'abjad' => 'A'],
    ['id' => 35, 'nama' => 'Asam Mefenamat', 'abjad' => 'A'],
    ['id' => 36, 'nama' => 'Asam Salisilat', 'abjad' => 'A'],
    ['id' => 37, 'nama' => 'Asam Traneksamat', 'abjad' => 'A'],
    ['id' => 38, 'nama' => 'Asam Ursodeoksikolat', 'abjad' => 'A'],
    ['id' => 39, 'nama' => 'Asam Valproat', 'abjad' => 'A'],
    ['id' => 40, 'nama' => 'Asenapine', 'abjad' => 'A'],
    ['id' => 41, 'nama' => 'Aselkolin', 'abjad' => 'A'],
    ['id' => 42, 'nama' => 'Aspirin', 'abjad' => 'A'],
    ['id' => 43, 'nama' => 'Astaxanthin', 'abjad' => 'A'],
    ['id' => 44, 'nama' => 'Astemizole', 'abjad' => 'A'],
    ['id' => 45, 'nama' => 'Atenolol', 'abjad' => 'A'],
    ['id' => 46, 'nama' => 'Atorvasn', 'abjad' => 'A'],
    ['id' => 47, 'nama' => 'Atropin', 'abjad' => 'A'],
    ['id' => 48, 'nama' => 'Aapulgite', 'abjad' => 'A'],
    ['id' => 49, 'nama' => 'Azatadine', 'abjad' => 'A'],
    ['id' => 50, 'nama' => 'Azathioprine', 'abjad' => 'A'],
    ['id' => 51, 'nama' => 'Azithromycin', 'abjad' => 'A'],
    ['id' => 52, 'nama' => 'Bacitracin', 'abjad' => 'B'],
    ['id' => 53, 'nama' => 'Baclofen', 'abjad' => 'B'],
    ['id' => 54, 'nama' => 'Bambuterol', 'abjad' => 'B'],
    ['id' => 55, 'nama' => 'Benazepril', 'abjad' => 'B'],
    ['id' => 56, 'nama' => 'Benzoyl Peroxide', 'abjad' => 'B'],
    ['id' => 57, 'nama' => 'Betametason', 'abjad' => 'B'],
    ['id' => 58, 'nama' => 'Bio n', 'abjad' => 'B'],
    ['id' => 59, 'nama' => 'Bisacodyl', 'abjad' => 'B'],
    ['id' => 60, 'nama' => 'Boron', 'abjad' => 'B'],
    ['id' => 61, 'nama' => 'Botulinum Toxin', 'abjad' => 'B'],
    ['id' => 62, 'nama' => 'Bromelain', 'abjad' => 'B'],
    ['id' => 63, 'nama' => 'Bromhexine', 'abjad' => 'B'],
    ['id' => 64, 'nama' => 'Bromocrip ne', 'abjad' => 'B'],
    ['id' => 65, 'nama' => 'Brompheniramine', 'abjad' => 'B'],
    ['id' => 66, 'nama' => 'Budesonide', 'abjad' => 'B'],
    ['id' => 67, 'nama' => 'Bupivacaine', 'abjad' => 'B'],
    ['id' => 68, 'nama' => 'Bupropion', 'abjad' => 'B'],
    ['id' => 69, 'nama' => 'Busulfan', 'abjad' => 'B'],
    ['id' => 70, 'nama' => 'Calcitriol', 'abjad' => 'C'],
    ['id' => 71, 'nama' => 'Calcium Acetate', 'abjad' => 'C'],
    ['id' => 72, 'nama' => 'Calcium Carbonate', 'abjad' => 'C'],
    ['id' => 73, 'nama' => 'Candesartan', 'abjad' => 'C'],
    ['id' => 74, 'nama' => 'Captopril', 'abjad' => 'C'],
    ['id' => 75, 'nama' => 'Carbamazepine', 'abjad' => 'C'],
    ['id' => 76, 'nama' => 'Carbimazole', 'abjad' => 'C'],
    ['id' => 77, 'nama' => 'Carvedilol', 'abjad' => 'C'],
    ['id' => 78, 'nama' => 'Caspo ungin', 'abjad' => 'C'],
    ['id' => 79, 'nama' => 'Ce adroxil', 'abjad' => 'C'],
    ['id' => 80, 'nama' => 'Ce azolin', 'abjad' => 'C'],
    ['id' => 81, 'nama' => 'Ce epime', 'abjad' => 'C'],
    ['id' => 82, 'nama' => 'Cefdinir', 'abjad' => 'C'],
    ['id' => 83, 'nama' => 'Cefxime', 'abjad' => 'C'],
    ['id' => 84, 'nama' => 'Ce operazone', 'abjad' => 'C'],
    ['id' => 85, 'nama' => 'Ce otaxim', 'abjad' => 'C'],
    ['id' => 86, 'nama' => 'Ce azidime', 'abjad' => 'C'],
    ['id' => 87, 'nama' => 'Ce riaxone', 'abjad' => 'C'],
    ['id' => 88, 'nama' => 'Ce uroxime', 'abjad' => 'C'],
    ['id' => 89, 'nama' => 'Celecoxib', 'abjad' => 'C'],
    ['id' => 90, 'nama' => 'Cephalexin', 'abjad' => 'C'],
    ['id' => 91, 'nama' => 'Ce rizine', 'abjad' => 'C'],
    ['id' => 92, 'nama' => 'Chlordiazepoxide', 'abjad' => 'C'],
    ['id' => 93, 'nama' => 'Chlorpheniramine', 'abjad' => 'C'],
    ['id' => 94, 'nama' => 'Chlorpromazine', 'abjad' => 'C'],
    ['id' => 95, 'nama' => 'Cholestyramine', 'abjad' => 'C'],
    ['id' => 96, 'nama' => 'Ciclosporin', 'abjad' => 'C'],
    ['id' => 97, 'nama' => 'Cilostazol', 'abjad' => 'C'],
    ['id' => 98, 'nama' => 'Cime dine', 'abjad' => 'C'],
    ['id' => 99, 'nama' => 'Cinnarizine', 'abjad' => 'C'],
    ['id' => 100, 'nama' => 'Cipro oxacin', 'abjad' => 'C'],
    ['id' => 101, 'nama' => 'Cispla n', 'abjad' => 'C'],
    ['id' => 102, 'nama' => 'Citalopram', 'abjad' => 'C'],
    ['id' => 103, 'nama' => 'Ci colin', 'abjad' => 'C'],
    ['id' => 104, 'nama' => 'Claritrhomycin', 'abjad' => 'C'],
    ['id' => 105, 'nama' => 'Clindamycin', 'abjad' => 'C'],
    ['id' => 106, 'nama' => 'Clobazam', 'abjad' => 'C'],
    ['id' => 107, 'nama' => 'Clonazepam', 'abjad' => 'C'],
    ['id' => 108, 'nama' => 'Clonidine', 'abjad' => 'C'],
    ['id' => 109, 'nama' => 'Clopidogrel', 'abjad' => 'C'],
    ['id' => 110, 'nama' => 'Clotrimazole', 'abjad' => 'C'],
    ['id' => 111, 'nama' => 'Clozapine', 'abjad' => 'C'],
    ['id' => 112, 'nama' => 'Co-trimoxazole (sul famethoxazole + trimethoprim)', 'abjad' => 'C'],
    ['id' => 113, 'nama' => 'Codeine', 'abjad' => 'C'],
    ['id' => 114, 'nama' => 'Coenzyme Q10', 'abjad' => 'C'],
    ['id' => 115, 'nama' => 'Colchicine', 'abjad' => 'C'],
    ['id' => 116, 'nama' => 'Colis n', 'abjad' => 'C'],
    ['id' => 117, 'nama' => 'Cor sone', 'abjad' => 'C'],
    ['id' => 118, 'nama' => 'Cyclophosphamide', 'abjad' => 'C'],
    ['id' => 119, 'nama' => 'Cyproheptadine', 'abjad' => 'C'],
    ['id' => 120, 'nama' => 'Dabigatran', 'abjad' => 'D'],
    ['id' => 121, 'nama' => 'Desloratadine', 'abjad' => 'D'],
    ['id' => 122, 'nama' => 'Desoximetasone', 'abjad' => 'D'],
    ['id' => 123, 'nama' => 'Dexamethasone', 'abjad' => 'D'],
    ['id' => 124, 'nama' => 'Dexchlorpheniramine', 'abjad' => 'D'],
    ['id' => 125, 'nama' => 'Dexketoprofen', 'abjad' => 'D'],
    ['id' => 126, 'nama' => 'Dextromethorphan', 'abjad' => 'D'],
    ['id' => 127, 'nama' => 'Dextrose', 'abjad' => 'D'],
    ['id' => 128, 'nama' => 'Diazepam', 'abjad' => 'D'],
    ['id' => 129, 'nama' => 'Diclofenac', 'abjad' => 'D'],
    ['id' => 130, 'nama' => 'Diethylcarbamazine', 'abjad' => 'D'],
    ['id' => 131, 'nama' => 'Digoxin', 'abjad' => 'D'],
    ['id' => 132, 'nama' => 'Dil azem', 'abjad' => 'D'],
    ['id' => 133, 'nama' => 'Dimenhydrinate', 'abjad' => 'D'],
    ['id' => 134, 'nama' => 'Dimethicone', 'abjad' => 'D'],
    ['id' => 135, 'nama' => 'Diphenhydramine', 'abjad' => 'D'],
    ['id' => 136, 'nama' => 'Disulfram', 'abjad' => 'D'],
    ['id' => 137, 'nama' => 'Dobutamine', 'abjad' => 'D'],
    ['id' => 138, 'nama' => 'Docosahexaenoic Acid (DHA)', 'abjad' => 'D'],
    ['id' => 139, 'nama' => 'Domperidone', 'abjad' => 'D'],
    ['id' => 140, 'nama' => 'Donepezil', 'abjad' => 'D'],
    ['id' => 141, 'nama' => 'Dopamine', 'abjad' => 'D'],
    ['id' => 142, 'nama' => 'Doripenem', 'abjad' => 'D'],
    ['id' => 143, 'nama' => 'Doxycycline', 'abjad' => 'D'],
    ['id' => 144, 'nama' => 'Duloxe ne', 'abjad' => 'D'],
    ['id' => 145, 'nama' => 'Enalapril', 'abjad' => 'E'],
    ['id' => 146, 'nama' => 'Eperisone', 'abjad' => 'E'],
    ['id' => 147, 'nama' => 'Ephedrine', 'abjad' => 'E'],
    ['id' => 148, 'nama' => 'Epinephrine', 'abjad' => 'E'],
    ['id' => 149, 'nama' => 'Erdosteine', 'abjad' => 'E'],
    ['id' => 150, 'nama' => 'Ergotamine', 'abjad' => 'E'],
    ['id' => 151, 'nama' => 'Erythromycin', 'abjad' => 'E'],
    ['id' => 152, 'nama' => 'Escitalopram', 'abjad' => 'E'],
    ['id' => 153, 'nama' => 'Esomeprazole', 'abjad' => 'E'],
    ['id' => 154, 'nama' => 'Estazolam', 'abjad' => 'E'],
    ['id' => 155, 'nama' => 'Estradiol', 'abjad' => 'E'],
    ['id' => 156, 'nama' => 'Estrogen', 'abjad' => 'E'],
    ['id' => 157, 'nama' => 'Ethambutol', 'abjad' => 'E'],
    ['id' => 158, 'nama' => 'Etodolac', 'abjad' => 'E'],
    ['id' => 159, 'nama' => 'Etoricoxib', 'abjad' => 'E'],
    ['id' => 160, 'nama' => 'Famo dine', 'abjad' => 'F'],
    ['id' => 161, 'nama' => 'Felodipine', 'abjad' => 'F'],
    ['id' => 162, 'nama' => 'Fenofbrate', 'abjad' => 'F'],
    ['id' => 163, 'nama' => 'Fentanyl', 'abjad' => 'F'],
    ['id' => 164, 'nama' => 'Ferrous Fumarate', 'abjad' => 'F'],
    ['id' => 165, 'nama' => 'Fexofenadine', 'abjad' => 'F'],
    ['id' => 166, 'nama' => 'Fibrinogen', 'abjad' => 'F'],
    ['id' => 167, 'nama' => 'Finasteride', 'abjad' => 'F'],
    ['id' => 168, 'nama' => 'Fluconazole', 'abjad' => 'F'],
    ['id' => 169, 'nama' => 'Flunarizin', 'abjad' => 'F'],
    ['id' => 170, 'nama' => 'Fluoxe ne', 'abjad' => 'F'],
    ['id' => 171, 'nama' => 'Fluphenazine', 'abjad' => 'F'],
    ['id' => 172, 'nama' => 'Fluvoxamine', 'abjad' => 'F'],
    ['id' => 173, 'nama' => 'Fondaparinux', 'abjad' => 'F'],
    ['id' => 174, 'nama' => 'Formaldehyde', 'abjad' => 'F'],
    ['id' => 175, 'nama' => 'Fosinopril', 'abjad' => 'F'],
    ['id' => 176, 'nama' => 'Furosemide', 'abjad' => 'F'],
    ['id' => 177, 'nama' => 'Gabapen n', 'abjad' => 'G'],
    ['id' => 178, 'nama' => 'Galantamine', 'abjad' => 'G'],
    ['id' => 179, 'nama' => 'Gemfbrozil', 'abjad' => 'G'],
    ['id' => 180, 'nama' => 'Gentamicin', 'abjad' => 'G'],
    ['id' => 181, 'nama' => 'Glibenclamide', 'abjad' => 'G'],
    ['id' => 182, 'nama' => 'Glimepiride', 'abjad' => 'G'],
    ['id' => 183, 'nama' => 'Gliquidone', 'abjad' => 'G'],
    ['id' => 184, 'nama' => 'Glucagon', 'abjad' => 'G'],
    ['id' => 185, 'nama' => 'Glucosamine', 'abjad' => 'G'],
    ['id' => 186, 'nama' => 'Glycerol', 'abjad' => 'G'],
    ['id' => 187, 'nama' => 'Glycopyrronium bromide', 'abjad' => 'G'],
    ['id' => 188, 'nama' => 'Granisetron', 'abjad' => 'G'],
    ['id' => 189, 'nama' => 'Griseofulvin', 'abjad' => 'G'],
    ['id' => 190, 'nama' => 'Guai enesin', 'abjad' => 'G'],
    ['id' => 191, 'nama' => 'Haloperidol', 'abjad' => 'H'],
    ['id' => 192, 'nama' => 'Heparin', 'abjad' => 'H'],
    ['id' => 193, 'nama' => 'Homochlorcyclizine dihydrochloride', 'abjad' => 'H'],
    ['id' => 194, 'nama' => 'Human Chorionic Gonadotropin (HCG)', 'abjad' => 'H'],
    ['id' => 195, 'nama' => 'Hydrochlorothiazide (HCTZ)', 'abjad' => 'H'],
    ['id' => 196, 'nama' => 'Hydrocor sone', 'abjad' => 'H'],
    ['id' => 197, 'nama' => 'Hydroquinone', 'abjad' => 'H'],
    ['id' => 198, 'nama' => 'Hyoscine', 'abjad' => 'H'],
    ['id' => 199, 'nama' => 'Hyoscyamine', 'abjad' => 'H'],
    ['id' => 200, 'nama' => 'Ibuprofen', 'abjad' => 'I'],
    ['id' => 201, 'nama' => 'Iloprost', 'abjad' => 'I'],
    ['id' => 202, 'nama' => 'Imipramine', 'abjad' => 'I'],
    ['id' => 203, 'nama' => 'Indinavir', 'abjad' => 'I'],
    ['id' => 204, 'nama' => 'Indomethacin', 'abjad' => 'I'],
    ['id' => 205, 'nama' => 'Insulin', 'abjad' => 'I'],
    ['id' => 206, 'nama' => 'Ipratropium bromide', 'abjad' => 'I'],
    ['id' => 207, 'nama' => 'Irbesartan', 'abjad' => 'I'],
    ['id' => 208, 'nama' => 'Isoniazid', 'abjad' => 'I'],
    ['id' => 209, 'nama' => 'Isosorbide Dinitrate', 'abjad' => 'I'],
    ['id' => 210, 'nama' => 'Isotreno in', 'abjad' => 'I'],
    ['id' => 211, 'nama' => 'Isoxsuorine HCII', 'abjad' => 'I'],
    ['id' => 212, 'nama' => 'Isradipine', 'abjad' => 'I'],
    ['id' => 213, 'nama' => 'Itraconazole', 'abjad' => 'I'],
    ['id' => 214, 'nama' => 'Ivermec n', 'abjad' => 'I'],
    ['id' => 215, 'nama' => 'Kanamycin', 'abjad' => 'K'],
    ['id' => 216, 'nama' => 'Kaolin', 'abjad' => 'K'],
    ['id' => 217, 'nama' => 'Ketamine', 'abjad' => 'K'],
    ['id' => 218, 'nama' => 'Ketoconazole', 'abjad' => 'K'],
    ['id' => 219, 'nama' => 'Ketoprofen', 'abjad' => 'K'],
    ['id' => 220, 'nama' => 'Ketorolac', 'abjad' => 'K'],
    ['id' => 221, 'nama' => 'Keto fen', 'abjad' => 'K'],
    ['id' => 222, 'nama' => 'Kloramfenikol', 'abjad' => 'K'],
    ['id' => 223, 'nama' => 'L-Glutamine (Glutamine)', 'abjad' => 'L'],
    ['id' => 224, 'nama' => 'Lac c Acid', 'abjad' => 'L'],
    ['id' => 225, 'nama' => 'Lactobacillus Acidophilus', 'abjad' => 'L'],
    ['id' => 226, 'nama' => 'Lactobacillus acidophilus', 'abjad' => 'L'],
    ['id' => 227, 'nama' => 'Lactulose', 'abjad' => 'L'],
    ['id' => 228, 'nama' => 'Lanolin', 'abjad' => 'L'],
    ['id' => 229, 'nama' => 'Lansoprazole', 'abjad' => 'L'],
    ['id' => 230, 'nama' => 'Levodopa', 'abjad' => 'L'],
    ['id' => 231, 'nama' => 'Levo oxacin', 'abjad' => 'L'],
    ['id' => 232, 'nama' => 'Levonorgestrel', 'abjad' => 'L'],
    ['id' => 233, 'nama' => 'Lidocaine', 'abjad' => 'L'],
    ['id' => 234, 'nama' => 'Lincomycin', 'abjad' => 'L'],
    ['id' => 235, 'nama' => 'Lisinopril', 'abjad' => 'L'],
    ['id' => 236, 'nama' => 'Lithium', 'abjad' => 'L'],
    ['id' => 237, 'nama' => 'Loperamide', 'abjad' => 'L'],
    ['id' => 238, 'nama' => 'Loratadine', 'abjad' => 'L'],
    ['id' => 239, 'nama' => 'Lorazepam', 'abjad' => 'L'],
    ['id' => 240, 'nama' => 'Losartan', 'abjad' => 'L'],
    ['id' => 241, 'nama' => 'Lovas n', 'abjad' => 'L'],
    ['id' => 242, 'nama' => 'Lutein', 'abjad' => 'L'],
    ['id' => 243, 'nama' => 'Lysine', 'abjad' => 'L'],
    ['id' => 244, 'nama' => 'Magnesium Hidroksida', 'abjad' => 'M'],
    ['id' => 245, 'nama' => 'Manitol', 'abjad' => 'M'],
    ['id' => 246, 'nama' => 'Mebhydrolin', 'abjad' => 'M'],
    ['id' => 247, 'nama' => 'Meloxicam', 'abjad' => 'M'],
    ['id' => 248, 'nama' => 'Meman ne', 'abjad' => 'M'],
    ['id' => 249, 'nama' => 'Meropenem', 'abjad' => 'M'],
    ['id' => 250, 'nama' => 'Metamfetamin', 'abjad' => 'M'],
    ['id' => 251, 'nama' => 'Metampicillin', 'abjad' => 'M'],
    ['id' => 252, 'nama' => 'Me formin', 'abjad' => 'M'],
    ['id' => 253, 'nama' => 'Methadone', 'abjad' => 'M'],
    ['id' => 254, 'nama' => 'Methisoprinol', 'abjad' => 'M'],
    ['id' => 255, 'nama' => 'Methotrexate', 'abjad' => 'M'],
    ['id' => 256, 'nama' => 'Methylcobalamin', 'abjad' => 'M'],
    ['id' => 257, 'nama' => 'Methylprednisolone', 'abjad' => 'M'],
    ['id' => 258, 'nama' => 'Me l Salisilat', 'abjad' => 'M'],
    ['id' => 259, 'nama' => 'Me ldopa', 'abjad' => 'M'],
    ['id' => 260, 'nama' => 'Metoclopramide', 'abjad' => 'M'],
    ['id' => 261, 'nama' => 'Metoprolol', 'abjad' => 'M'],
    ['id' => 262, 'nama' => 'Metronidazole', 'abjad' => 'M'],
    ['id' => 263, 'nama' => 'Miconazole', 'abjad' => 'M'],
    ['id' => 264, 'nama' => 'Midazolam', 'abjad' => 'M'],
    ['id' => 265, 'nama' => 'Minoxidil', 'abjad' => 'M'],
    ['id' => 266, 'nama' => 'Misoprostol', 'abjad' => 'M'],
    ['id' => 267, 'nama' => 'Modafnil', 'abjad' => 'M'],
    ['id' => 268, 'nama' => 'Montelukast', 'abjad' => 'M'],
    ['id' => 269, 'nama' => 'Morfn', 'abjad' => 'M'],
    ['id' => 270, 'nama' => 'Moxi oxacin', 'abjad' => 'M'],
    ['id' => 271, 'nama' => 'Mupirocin', 'abjad' => 'M'],
    ['id' => 272, 'nama' => 'Naltrexone', 'abjad' => 'N'],
    ['id' => 273, 'nama' => 'Naproxen', 'abjad' => 'N'],
    ['id' => 274, 'nama' => 'Nateglinide', 'abjad' => 'N'],
    ['id' => 275, 'nama' => 'Natrium Bikarbonat', 'abjad' => 'N'],
    ['id' => 276, 'nama' => 'Nebivolol', 'abjad' => 'N'],
    ['id' => 277, 'nama' => 'Nedocromil', 'abjad' => 'N'],
    ['id' => 278, 'nama' => 'Nefazodone', 'abjad' => 'N'],
    ['id' => 279, 'nama' => 'Neomycin', 'abjad' => 'N'],
    ['id' => 280, 'nama' => 'Neos gmine', 'abjad' => 'N'],
    ['id' => 281, 'nama' => 'Nepafenac', 'abjad' => 'N'],
    ['id' => 282, 'nama' => 'Nesiri de', 'abjad' => 'N'],
    ['id' => 283, 'nama' => 'Nicardipine', 'abjad' => 'N'],
    ['id' => 284, 'nama' => 'Nicorandil', 'abjad' => 'N'],
    ['id' => 285, 'nama' => 'Nico namide', 'abjad' => 'N'],
    ['id' => 286, 'nama' => 'Ni fedipine', 'abjad' => 'N'],
    ['id' => 287, 'nama' => 'Ni furoxazide', 'abjad' => 'N'],
    ['id' => 288, 'nama' => 'Nilo nib', 'abjad' => 'N'],
    ['id' => 289, 'nama' => 'Nimorazole', 'abjad' => 'N'],
    ['id' => 290, 'nama' => 'Nimus ne', 'abjad' => 'N'],
    ['id' => 291, 'nama' => 'Nisoldipine', 'abjad' => 'N'],
    ['id' => 292, 'nama' => 'Nitrazepam', 'abjad' => 'N'],
    ['id' => 293, 'nama' => 'Nitro furantoin', 'abjad' => 'N'],
    ['id' => 294, 'nama' => 'Nitrogliserin', 'abjad' => 'N'],
    ['id' => 295, 'nama' => 'Niza dine', 'abjad' => 'N'],
    ['id' => 296, 'nama' => 'Nordazepam', 'abjad' => 'N'],
    ['id' => 297, 'nama' => 'Norepinephrine', 'abjad' => 'N'],
    ['id' => 298, 'nama' => 'Norethisterone', 'abjad' => 'N'],
    ['id' => 299, 'nama' => 'Noscapine', 'abjad' => 'N'],
    ['id' => 300, 'nama' => 'Nys n', 'abjad' => 'N'],
    ['id' => 301, 'nama' => 'Pantoprazole', 'abjad' => 'P'],
    ['id' => 302, 'nama' => 'Papaverine', 'abjad' => 'P'],
    ['id' => 303, 'nama' => 'Paracetamol', 'abjad' => 'P'],
    ['id' => 304, 'nama' => 'Parecoxib', 'abjad' => 'P'],
    ['id' => 305, 'nama' => 'Paromomycin', 'abjad' => 'P'],
    ['id' => 306, 'nama' => 'Pe oxacin', 'abjad' => 'P'],
    ['id' => 307, 'nama' => 'Penbutolol', 'abjad' => 'P'],
    ['id' => 308, 'nama' => 'Penciclovir', 'abjad' => 'P'],
    ['id' => 309, 'nama' => 'Perindopril', 'abjad' => 'P'],
    ['id' => 310, 'nama' => 'Permethrin', 'abjad' => 'P'],
    ['id' => 311, 'nama' => 'Phenobarbital', 'abjad' => 'P'],
    ['id' => 312, 'nama' => 'Phenylbutazone', 'abjad' => 'P'],
    ['id' => 313, 'nama' => 'Phenylephrine', 'abjad' => 'P'],
    ['id' => 314, 'nama' => 'Phenylpropanolamine', 'abjad' => 'P'],
    ['id' => 315, 'nama' => 'Phenytoin', 'abjad' => 'P'],
    ['id' => 316, 'nama' => 'Pilocarpine', 'abjad' => 'P'],
    ['id' => 317, 'nama' => 'Pioglitazone', 'abjad' => 'P'],
    ['id' => 318, 'nama' => 'Piracetam', 'abjad' => 'P'],
    ['id' => 319, 'nama' => 'Piroxicam', 'abjad' => 'P'],
    ['id' => 320, 'nama' => 'Policresulen', 'abjad' => 'P'],
    ['id' => 321, 'nama' => 'Potassium Acetate', 'abjad' => 'P'],
    ['id' => 322, 'nama' => 'Povidone Iodine', 'abjad' => 'P'],
    ['id' => 323, 'nama' => 'Pramipexole', 'abjad' => 'P'],
    ['id' => 324, 'nama' => 'Praziquantel', 'abjad' => 'P'],
    ['id' => 325, 'nama' => 'Prednisolone', 'abjad' => 'P'],
    ['id' => 326, 'nama' => 'Prednisone', 'abjad' => 'P'],
    ['id' => 327, 'nama' => 'Pregabalin', 'abjad' => 'P'],
    ['id' => 328, 'nama' => 'Probenecid', 'abjad' => 'P'],
    ['id' => 329, 'nama' => 'Procainamide', 'abjad' => 'P'],
    ['id' => 330, 'nama' => 'Prochlorperazine', 'abjad' => 'P'],
    ['id' => 331, 'nama' => 'Progesteron', 'abjad' => 'P'],
    ['id' => 332, 'nama' => 'Promethazine', 'abjad' => 'P'],
    ['id' => 333, 'nama' => 'Propo ol', 'abjad' => 'P'],
    ['id' => 334, 'nama' => 'Propranolol', 'abjad' => 'P'],
    ['id' => 335, 'nama' => 'Propylthiouracil', 'abjad' => 'P'],
    ['id' => 336, 'nama' => 'Pseudoephedrine', 'abjad' => 'P'],
    ['id' => 337, 'nama' => 'Pyrazinamide', 'abjad' => 'P'],
    ['id' => 338, 'nama' => 'Pyridoxine', 'abjad' => 'P'],
    ['id' => 339, 'nama' => 'Quinidine', 'abjad' => 'Q'],
    ['id' => 340, 'nama' => 'Quinine', 'abjad' => 'Q'],
    ['id' => 341, 'nama' => 'Radium', 'abjad' => 'R'],
    ['id' => 342, 'nama' => 'Ramipril', 'abjad' => 'R'],
    ['id' => 343, 'nama' => 'Rani din', 'abjad' => 'R'],
    ['id' => 344, 'nama' => 'Ranolazine', 'abjad' => 'R'],
    ['id' => 345, 'nama' => 'Regdanvimab', 'abjad' => 'R'],
    ['id' => 346, 'nama' => 'Resorcinol', 'abjad' => 'R'],
    ['id' => 347, 'nama' => 'Riboavin', 'abjad' => 'R'],
    ['id' => 348, 'nama' => 'Rifabu n', 'abjad' => 'R'],
    ['id' => 349, 'nama' => 'Rifampicin', 'abjad' => 'R'],
    ['id' => 350, 'nama' => 'Risperidone', 'abjad' => 'R'],
    ['id' => 351, 'nama' => 'Rivas gmine', 'abjad' => 'R'],
    ['id' => 352, 'nama' => 'Ropinirole', 'abjad' => 'R'],
    ['id' => 353, 'nama' => 'Rosuvas n', 'abjad' => 'R'],
    ['id' => 354, 'nama' => 'Saccharomyces boulardii Iyo', 'abjad' => 'S'],
    ['id' => 355, 'nama' => 'Salbutamol', 'abjad' => 'S'],
    ['id' => 356, 'nama' => 'Salmeterol', 'abjad' => 'S'],
    ['id' => 357, 'nama' => 'Satranidazole', 'abjad' => 'S'],
    ['id' => 358, 'nama' => 'Scopolamine', 'abjad' => 'S'],
    ['id' => 359, 'nama' => 'Sea Water', 'abjad' => 'S'],
    ['id' => 360, 'nama' => 'Secukinumab', 'abjad' => 'S'],
    ['id' => 361, 'nama' => 'Selegenile', 'abjad' => 'S'],
    ['id' => 362, 'nama' => 'Sertraline', 'abjad' => 'S'],
    ['id' => 363, 'nama' => 'Sildenafl', 'abjad' => 'S'],
    ['id' => 364, 'nama' => 'Simethicone', 'abjad' => 'S'],
    ['id' => 365, 'nama' => 'Simvas n', 'abjad' => 'S'],
    ['id' => 366, 'nama' => 'Spiramycin', 'abjad' => 'S'],
    ['id' => 367, 'nama' => 'Spironolactone', 'abjad' => 'S'],
    ['id' => 368, 'nama' => 'Squalene', 'abjad' => 'S'],
    ['id' => 369, 'nama' => 'Streptokinase', 'abjad' => 'S'],
    ['id' => 370, 'nama' => 'Streptomycin', 'abjad' => 'S'],
    ['id' => 371, 'nama' => 'Stron um', 'abjad' => 'S'],
    ['id' => 372, 'nama' => 'Sukralfat', 'abjad' => 'S'],
    ['id' => 373, 'nama' => 'Sulfadizine', 'abjad' => 'S'],
    ['id' => 374, 'nama' => 'Sul famethoxazole', 'abjad' => 'S'],
    ['id' => 375, 'nama' => 'Sulfanilamide', 'abjad' => 'S'],
    ['id' => 376, 'nama' => 'Sul fasalazine', 'abjad' => 'S'],
    ['id' => 377, 'nama' => 'Sumatripan', 'abjad' => 'S'],
    ['id' => 378, 'nama' => 'Tadalafl', 'abjad' => 'T'],
    ['id' => 379, 'nama' => 'Ta u prost', 'abjad' => 'T'],
    ['id' => 380, 'nama' => 'Tamoxi en', 'abjad' => 'T'],
    ['id' => 381, 'nama' => 'Tamsulosin', 'abjad' => 'T'],
    ['id' => 382, 'nama' => 'Telmisartan', 'abjad' => 'T'],
    ['id' => 383, 'nama' => 'Temazepan', 'abjad' => 'T'],
    ['id' => 384, 'nama' => 'Tembaga', 'abjad' => 'T'],
    ['id' => 385, 'nama' => 'Teno ovir', 'abjad' => 'T'],
    ['id' => 386, 'nama' => 'Teoflin', 'abjad' => 'T'],
    ['id' => 387, 'nama' => 'Terazosin', 'abjad' => 'T'],
    ['id' => 388, 'nama' => 'Terbinafne', 'abjad' => 'T'],
    ['id' => 389, 'nama' => 'Terbutaline', 'abjad' => 'T'],
    ['id' => 390, 'nama' => 'Testosterone', 'abjad' => 'T'],
    ['id' => 391, 'nama' => 'Tetracycline', 'abjad' => 'T'],
    ['id' => 392, 'nama' => 'Thalimode', 'abjad' => 'T'],
    ['id' => 393, 'nama' => 'Thiamphenicole', 'abjad' => 'T'],
    ['id' => 394, 'nama' => 'Tiabendazole', 'abjad' => 'T'],
    ['id' => 395, 'nama' => 'Ticlopidine', 'abjad' => 'T'],
    ['id' => 396, 'nama' => 'Timolon', 'abjad' => 'T'],
    ['id' => 397, 'nama' => 'Tizanidine', 'abjad' => 'T'],
    ['id' => 398, 'nama' => 'Tobramycin', 'abjad' => 'T'],
    ['id' => 399, 'nama' => 'Tramadol', 'abjad' => 'T'],
    ['id' => 400, 'nama' => 'Treno in', 'abjad' => 'T'],
    ['id' => 401, 'nama' => 'Triamcinolone', 'abjad' => 'T'],
    ['id' => 402, 'nama' => 'Triclosan', 'abjad' => 'T'],
    ['id' => 403, 'nama' => 'Trihexyphenidyl', 'abjad' => 'T'],
    ['id' => 404, 'nama' => 'Trimethoprin', 'abjad' => 'T'],
    ['id' => 405, 'nama' => 'Triprolidine', 'abjad' => 'T'],
    ['id' => 406, 'nama' => 'Tripsin', 'abjad' => 'T'],
    ['id' => 407, 'nama' => 'Vaksin BCG', 'abjad' => 'V'],
    ['id' => 408, 'nama' => 'Valacyclovir', 'abjad' => 'V'],
    ['id' => 409, 'nama' => 'Valsartan', 'abjad' => 'V'],
    ['id' => 410, 'nama' => 'Vancomycin', 'abjad' => 'V'],
    ['id' => 411, 'nama' => 'Vasopressin', 'abjad' => 'V'],
    ['id' => 412, 'nama' => 'Verapamil', 'abjad' => 'V'],
    ['id' => 413, 'nama' => 'Vildaglip n', 'abjad' => 'V'],
    ['id' => 414, 'nama' => 'Vincris ne', 'abjad' => 'V'],
    ['id' => 415, 'nama' => 'Vitamin A', 'abjad' => 'V'],
    ['id' => 416, 'nama' => 'Vitamin B1', 'abjad' => 'V'],
    ['id' => 417, 'nama' => 'Vitamin B12', 'abjad' => 'V'],
    ['id' => 418, 'nama' => 'Vitamin B2', 'abjad' => 'V'],
    ['id' => 419, 'nama' => 'Vitamin B3 (Niacin)', 'abjad' => 'V'],
    ['id' => 420, 'nama' => 'Vitamin B5', 'abjad' => 'V'],
    ['id' => 21, 'nama' => 'Vitamin B6', 'abjad' => 'V'],
    ['id' => 422, 'nama' => 'Vitamin B9 (Asam Volat)', 'abjad' => 'V'],
    ['id' => 423, 'nama' => 'Vitamin C', 'abjad' => 'V'],
    ['id' => 424, 'nama' => 'Vitamin D', 'abjad' => 'V'],
    ['id' => 425, 'nama' => 'Vitamin E', 'abjad' => 'V'],
    ['id' => 426, 'nama' => 'Vitamin K', 'abjad' => 'V'],
    ['id' => 427, 'nama' => 'Warfarin', 'abjad' => 'W'],
    ['id' => 428, 'nama' => 'White petrolatum', 'abjad' => 'W'],
    ['id' => 429, 'nama' => 'Zinc Sulfat', 'abjad' => 'Z'],
    ['id' => 430, 'nama' => 'Zolpidem', 'abjad' => 'Z'],
];

// Array untuk A-Z filter
$alphabet = range('A', 'Z');
?>

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>SagaHealth</title>
  <link rel="icon" href="../assets/img/tittle.png" type="image/png">
    
    <link rel="stylesheet" href="../assets/style/partials.css">
     <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>
<body class="font-sans bg-white">

<?php include '../partials/header.php'; ?>

    <main>

        <section class="kamus-hero">
            <div class="container-wrapper text-center">
                <h1>Kamus Kesehatan</h1>
                <p class="about-subtitle">
                    Temukan informasi lengkap mengenai penyakit dan obat-obatan.
                </p>
            </div>
        </section>

        <section class="kamus-section">
            <div class="container-wrapper">
                
                <div class="tab-nav">
                    <button class="tab-button active" data-tab="tab-penyakit">
                        <i class="fas fa-stethoscope"></i> Daftar Penyakit
                    </button>
                    <button class="tab-button" data-tab="tab-obat">
                        <i class="fas fa-pills"></i> Daftar Obat
                    </button>
                </div>

                <div class="tab-content-container">
                    
                    <div class="tab-content active" id="tab-penyakit">
                        
                        <div class="az-filter" id="filter-penyakit">
                            <button class="az-button" data-letter="all">Semua</button>
                            <?php foreach ($alphabet as $letter): ?>
                                <button class="az-button" data-letter="<?php echo $letter; ?>"><?php echo $letter; ?></button>
                            <?php endforeach; ?>
                        </div>

                        <ul id="list-penyakit" class="kamus-list">
                            <?php foreach ($penyakit as $item): ?>
                                <?php
                                    // Ambil huruf pertama dari nama untuk data-letter
                                    $firstLetter = strtoupper(substr($item['nama'], 0, 1));
                                ?>
                                <li data-letter="<?php echo $firstLetter; ?>">
                                    <a href="#">
                                        <?php echo htmlspecialchars($item['nama']); ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>

                    </div>
                    
                    <div class="tab-content" id="tab-obat">
                        
                        <div class="az-filter" id="filter-obat">
                            <button class="az-button" data-letter="all">Semua</button>
                            <?php foreach ($alphabet as $letter): ?>
                                <button class="az-button" data-letter="<?php echo $letter; ?>"><?php echo $letter; ?></button>
                            <?php endforeach; ?>
                        </div>

                        <ul id="list-obat" class="kamus-list">
                            <?php foreach ($obat as $item): ?>
                                <li data-letter="<?php echo htmlspecialchars($item['abjad']); ?>">
                                    <a href="#">
                                        <?php echo htmlspecialchars($item['nama']); ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        
                    </div>

                </div>

            </div>
        </section>

    </main>

<?php include '../partials/footer.php'; ?>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            
            // === Skrip Menu Mobile (dari halaman lain) ===
            const menuToggle = document.getElementById('mobile-menu-toggle');
            const navMenu = document.getElementById('main-nav-menu');

            if (menuToggle && navMenu) {
                menuToggle.addEventListener('click', () => {
                    navMenu.classList.toggle('active');
                });
            }

            // === Skrip Tab Kamus Kesehatan ===
            const tabButtons = document.querySelectorAll('.tab-button');
            const tabContents = document.querySelectorAll('.tab-content');

            tabButtons.forEach(button => {
                button.addEventListener('click', () => {
                    const tabId = button.getAttribute('data-tab');

                    // Nonaktifkan semua tombol dan konten
                    tabButtons.forEach(btn => btn.classList.remove('active'));
                    tabContents.forEach(content => content.classList.remove('active'));

                    // Aktifkan tombol dan konten yang dipilih
                    button.classList.add('active');
                    document.getElementById(tabId).classList.add('active');
                });
            });

            // === Skrip Filter A-Z (Reusable) ===
            function setupAzFilter(filterId, listId) {
                const filterContainer = document.getElementById(filterId);
                const listContainer = document.getElementById(listId);
                if (!filterContainer || !listContainer) return;

                const listItems = listContainer.querySelectorAll('li');
                const filterButtons = filterContainer.querySelectorAll('.az-button');

                filterContainer.addEventListener('click', (e) => {
                    if (!e.target.classList.contains('az-button')) return;

                    const letter = e.target.getAttribute('data-letter');

                    // Atur status aktif pada tombol filter
                    filterButtons.forEach(btn => btn.classList.remove('active'));
                    e.target.classList.add('active');

                    // Tampilkan/sembunyikan item daftar
                    listItems.forEach(item => {
                        if (letter === 'all' || item.getAttribute('data-letter') === letter) {
                            item.style.display = 'block';
                        } else {
                            item.style.display = 'none';
                        }
                    });
                });

                // Default: klik tombol "Semua"
                filterContainer.querySelector('.az-button[data-letter="all"]').click();
            }

            // Terapkan filter ke kedua daftar
            setupAzFilter('filter-penyakit', 'list-penyakit');
            setupAzFilter('filter-obat', 'list-obat');
            
        });
    </script>
    
</body>
</html>